development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:p67060958dfa646a8b725cf40a2432a2869c145e29f8fab252762ccd60020de3f@ec2-35-169-18-251.compute-1.amazonaws.com:14219
  # channel_prefix: mafia-server_production
